package ch.admin.bit.jeap.doc.sitegenerator;

import ch.admin.bit.jeap.doc.domain.DisplayTime;
import ch.admin.bit.jeap.doc.domain.DocumentationFacts;
import ch.admin.bit.jeap.doc.domain.SiteEnvironment;
import ch.admin.bit.jeap.doc.domain.architecture.imports.ImportOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * What the page describing the documentation says.
 * <p>
 * Two of these matter more than the rest: that the page names <b>its own</b> build rather than a number from
 * some other run, and that it reads correctly for somebody whose browser runs no scripts - the numbers of the
 * run and the live status both arrive by fetch, and a page with a hole in it where they belong would be worse
 * than one that says where they are.
 * <p>
 * The third is what the page does <b>not</b> say. Everything that moves with the clock is gone from it, so
 * that a tree whose documentation has not moved can be left as it is; what those statements read as is
 * asserted in {@code DocumentationProvenanceTest}.
 */
class AboutThisDocumentationTest {

    private static final Instant GENERATED_AT = Instant.parse("2026-09-03T07:30:00Z");
    private static final Instant IMPORTED_AT = Instant.parse("2026-09-03T05:45:00Z");
    private static final String STATUS_URL = "https://doc.example.ch/docs/about-this-documentation.json";
    private static final String LIVE_STATUS_URL = "https://doc.example.ch/docs/live-status.json";

    @TempDir
    Path directory;

    private final AboutThisDocumentation page = new AboutThisDocumentation();

    @Test
    void write_thenThePageNamesItsOwnBuildAndWhereItsNumbersAre() throws IOException {
        String written = write(facts(), 4711L);

        // The whole sentence, because two things hang on its wording: it has to read on its own for a reader
        // whose browser runs no scripts, and the phrase naming the build is what the content digest replaces
        // before hashing - see SiteSources. It also must not promise a number the run no longer reports.
        assertThat(written).contains("This site was generated by build `4711` on "
                                     + DisplayTime.of(GENERATED_AT) + ". How long that run took is published "
                                     + "beside this page as [about-this-documentation.json](" + STATUS_URL
                                     + "), because a page cannot describe the build that writes it.");
        assertThat(written).describedAs("and it promises no page count and no size: a site is built one part "
                                        + "at a time, and only this part's numbers are ever served")
                .doesNotContain("its pages");
    }

    @Test
    void write_thenTheFrontMatterSaysItIsGeneratedByTheServiceItself() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .startsWith("---")
                .contains("doc_status: \"generated\"")
                .contains("doc_source: \"doc-service\"")
                .contains("doc_environment: \"prod\"")
                .contains("doc_generated_at: \"2026-09-03T07:30:00Z\"")
                .contains("sidebar_position: 2");
    }

    /**
     * The counts come from the run, and an environment that reads no architecture model says so rather than
     * showing zeros - a zero would read as a landscape with nothing in it.
     */
    @Test
    void write_thenEachEnvironmentSaysWhatItsModelContributed() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .contains("2 systems, 5 components, 9 messages")
                .contains("*no architecture model*")
                .contains(DisplayTime.of(IMPORTED_AT))
                .doesNotContain("(unchanged)");
    }

    /**
     * <b>The page carries provenance and no status.</b> When the content was imported stays true while the
     * page is not rebuilt; when the repository was last read, whether the import is behind, and when the
     * schedule fires next do not - so none of them is written into the page at all. The row of the environment
     * whose repository was read a quarter of an hour ago is the one that would carry them.
     */
    @Test
    void write_thenWhatWouldGoStaleIsNotOnThePage() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .doesNotContain("last read")
                .doesNotContain("not read since")
                .doesNotContain("the last run did not read it")
                .doesNotContain(DisplayTime.of(Instant.parse("2026-09-03T07:15:00Z")))
                .describedAs("the moment the import fires next, as the row used to print it")
                .doesNotContain("in 15 minutes");
    }

    /**
     * And it names where they are, so that the page reads correctly for a reader whose browser runs no
     * scripts - and so that the client module and the reader follow the same URL.
     */
    @Test
    void write_thenItNamesWhereTheLiveStateIs() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .contains("[live-status.json](" + LIVE_STATUS_URL + ")")
                .contains("**Last read**")
                .contains("**Next**")
                .contains("the state right now rather than part of this publication");
    }

    /**
     * A stage whose architecture repository reports no system at all is imported successfully, hour after
     * hour, and stores no row - so there is no content timestamp. Saying <i>never</i> reported a working
     * import as a missing one, so the cell is left for the live status to speak for.
     */
    @Test
    void write_whenTheLandscapeIsEmptyButImported_thenItDoesNotCallTheImportNever() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null));

        page.write(facts, new SiteEnvironment("prod", "PROD", "Production", 1, true, false),
                Map.of("prod", EnvironmentModel.empty(null)), 1L, STATUS_URL, LIVE_STATUS_URL, directory);

        String written = Files.readString(directory.resolve(AboutThisDocumentation.FILE_NAME),
                StandardCharsets.UTF_8);
        assertThat(written).doesNotContain("*never*");
    }

    /**
     * One schedule, because there is one: the import reads the landscape and asks for every part of the site.
     * The expression is configuration and is printed; the cell beside it is left for the live status.
     */
    @Test
    void write_thenTheScheduleIsPrintedAndItsNextOccurrenceIsLeftToTheLiveStatus() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .contains("| The architecture model is imported, and the site published | "
                          + "`0 45 5-19 * * *` | - |")
                .doesNotContain("`0 5 6-20 * * *`");
    }

    /**
     * A site no architecture repository feeds is published when something is uploaded to it, and the page says
     * that rather than leaving the cell empty.
     */
    @Test
    void write_whenNoImportFeedsTheSite_thenItSaysSoRatherThanLeavingTheCellEmpty()
            throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null));

        String written = write(facts, 1L);

        assertThat(written).contains("*only when something is uploaded to this site*");
    }

    @Test
    void write_whenTheVersionCannotBeRead_thenThePageSaysNothingAboutIt() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service(null, GENERATED_AT), site(), List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null));

        String written = write(facts, 1L);

        assertThat(written).contains("generated by the jEAP Doc Service.").doesNotContain("null");
    }

    /** Two systems, because what this page says about them is their number. */
    private static java.util.List<EnvironmentModel.DocumentedSystemEntry> twoSystems() {
        return java.util.List.of(
                new EnvironmentModel.DocumentedSystemEntry("orders", "/systems/orders/"),
                new EnvironmentModel.DocumentedSystemEntry("shipping", "/systems/shipping/"));
    }

    private String write(DocumentationFacts facts, long buildId) throws IOException {
        page.write(facts, new SiteEnvironment("prod", "PROD", "Production", 1, true, false),
                Map.of("prod", new EnvironmentModel(twoSystems(), 5, 9, IMPORTED_AT)), buildId, STATUS_URL,
                LIVE_STATUS_URL, directory);
        return Files.readString(directory.resolve(AboutThisDocumentation.FILE_NAME), StandardCharsets.UTF_8);
    }

    private static DocumentationFacts facts() {
        return new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT),
                site(),
                List.of(environmentFacts(),
                        new DocumentationFacts.EnvironmentFacts("dev", "Development", false, true, false,
                                null, null, Duration.ofHours(2))),
                new DocumentationFacts.Schedules("0 45 5-19 * * *",
                        GENERATED_AT.plus(Duration.ofMinutes(15))));
    }

    /**
     * <b>A page that contradicts itself is a support call.</b> Every test above builds the same site - with a
     * structure template, and publishing on upload - so neither of the two branches the page carries for the
     * other configuration was written by any of them. These three are that configuration.
     */
    @Test
    void write_whenAnUploadDoesNotPublishTheSite_thenThePageSaysSoOnlyOnce() throws IOException {
        DocumentationFacts all = facts();
        DocumentationFacts facts = new DocumentationFacts(all.service(),
                new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                        List.of("System Architecture"), true, false, 3),
                all.environments(),
                // No import feeds it either, so the row falls back to what does publish it.
                new DocumentationFacts.Schedules(null, null));

        String written = write(facts, 4711L);

        assertThat(written)
                .contains("| An upload publishes the site | no |")
                .contains("*only when an operator asks for it*")
                .describedAs("the paragraph that says the opposite belongs to the other configuration")
                .doesNotContain("as soon as it arrives");
    }

    @Test
    void write_whenThereIsNoStructureTemplate_thenWhatIsStillGeneratedIsNamed() throws IOException {
        String written = write(factsOf(new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                List.of(), true, true, 3)), 4711L);

        assertThat(written)
                .describedAs("an environment of this site does read a model, so those pages exist")
                .contains("*none - only the system index and the landing pages are generated*");
    }

    /**
     * With no architecture repository for any environment, {@code SystemPages.write} returns before it creates
     * a directory - so neither a system index nor a landing page exists, and naming them would be the same
     * untruth the other way round.
     */
    @Test
    void write_whenNoEnvironmentReadsAModel_thenNoGeneratedPagesAreClaimed() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT),
                new DocumentationFacts.SiteFacts("default", "Platform Documentation", List.of(), false, true, 3),
                List.of(new DocumentationFacts.EnvironmentFacts("prod", "Production", true, true, false,
                        null, null, Duration.ofHours(2))),
                new DocumentationFacts.Schedules(null, null));

        String written = write(facts, 4711L);

        assertThat(written).contains("| Documentation structures | *none* |")
                .doesNotContain("the system index and the landing pages");
    }

    private static DocumentationFacts factsOf(DocumentationFacts.SiteFacts site) {
        DocumentationFacts all = facts();
        return new DocumentationFacts(all.service(), site, all.environments(), all.schedules());
    }

    private static DocumentationFacts.SiteFacts site() {
        return new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                List.of("System Architecture"), true, true, 3);
    }

    private static DocumentationFacts.EnvironmentFacts environmentFacts() {
        return new DocumentationFacts.EnvironmentFacts("prod", "Production", true, false, true,
                Instant.parse("2026-09-03T07:15:00Z"), ImportOutcome.UNCHANGED, Duration.ofHours(2));
    }
}
