package ch.admin.bit.jeap.doc.sitegenerator;

import ch.admin.bit.jeap.doc.domain.DisplayTime;
import ch.admin.bit.jeap.doc.domain.DocumentationFacts;
import ch.admin.bit.jeap.doc.domain.SiteEnvironment;
import ch.admin.bit.jeap.doc.domain.architecture.imports.ImportOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * What the page describing the documentation says.
 * <p>
 * Two of these matter more than the rest: that the page names <b>its own</b> build rather than a number from
 * some other run, and that it reads correctly for somebody whose browser runs no scripts - the five metrics
 * arrive by fetch, and a page with a hole in it where they belong would be worse than one that says where they
 * are.
 */
class AboutThisDocumentationTest {

    private static final Instant GENERATED_AT = Instant.parse("2026-09-03T07:30:00Z");
    private static final Instant IMPORTED_AT = Instant.parse("2026-09-03T05:45:00Z");
    private static final String STATUS_URL = "https://doc.example.ch/docs/about-this-documentation.json";

    @TempDir
    Path directory;

    private final AboutThisDocumentation page = new AboutThisDocumentation();

    @Test
    void write_thenThePageNamesItsOwnBuildAndWhereItsNumbersAre() throws IOException {
        String written = write(facts(), 4711L);

        assertThat(written)
                .contains("generated by build `4711`")
                .contains("[about-this-documentation.json](" + STATUS_URL + ")")
                .describedAs("the sentence has to read on its own, with no scripts at all")
                .contains("because a page cannot describe the build that writes it");
    }

    @Test
    void write_thenTheFrontMatterSaysItIsGeneratedByTheServiceItself() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .startsWith("---")
                .contains("doc_status: \"generated\"")
                .contains("doc_source: \"doc-service\"")
                .contains("doc_environment: \"prod\"")
                .contains("doc_generated_at: \"2026-09-03T07:30:00Z\"")
                .contains("sidebar_position: 2");
    }

    /**
     * The counts come from the run, and an environment that reads no architecture model says so rather than
     * showing zeros - a zero would read as a landscape with nothing in it.
     */
    @Test
    void write_thenEachEnvironmentSaysWhatItsModelContributed() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .contains("2 systems, 5 components, 9 messages")
                .contains("*no architecture model*")
                // The outcome of a successful run is not named: the content timestamp beside it already says
                // whether the landscape changed, and naming it invited the reading that a failed run's word
                // belonged to the timestamp of the successful one.
                .contains(DisplayTime.of(IMPORTED_AT) + ", last read "
                          + DisplayTime.of(Instant.parse("2026-09-03T07:15:00Z")))
                .doesNotContain("(unchanged)");
    }

    /**
     * A stage whose architecture repository reports no system at all is imported successfully, hour after
     * hour, and stores no row - so there is no content timestamp. Calling that <i>never</i> reported a working
     * import as a missing one.
     */
    @Test
    void write_whenTheLandscapeIsEmptyButImported_thenItSaysWhenItWasReadRatherThanNever() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null, null, null));

        page.write(facts, new SiteEnvironment("prod", "PROD", "Production", 1, true, false),
                Map.of("prod", EnvironmentModel.empty(null)), 1L, STATUS_URL, directory);

        String written = Files.readString(directory.resolve(AboutThisDocumentation.FILE_NAME),
                StandardCharsets.UTF_8);
        assertThat(written).doesNotContain("*never*");
        assertThat(written).contains("last read " + DisplayTime.of(Instant.parse("2026-09-03T07:15:00Z")));
    }

    /**
     * The outcome belongs to the latest run and the timestamp to the last successful one, so joining them said
     * that the read which worked did not.
     */
    @Test
    void write_whenTheLastRunFailed_thenTheTimestampIsNotBlamedForIt() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(new DocumentationFacts.EnvironmentFacts("prod", "Production", true, false, true,
                        Instant.parse("2026-09-03T04:00:00Z"), ImportOutcome.FAILED, Duration.ofHours(2))),
                new DocumentationFacts.Schedules(null, null, null, null));

        String written = write(facts, 1L);

        assertThat(written)
                .doesNotContain("(failed)")
                .contains("last read " + DisplayTime.of(Instant.parse("2026-09-03T04:00:00Z")))
                .describedAs("three and a half hours, against a two-hour staleness measure")
                .contains("; not read since");
    }

    /** A run that failed while the import is still within its measure is not yet 'not read since'. */
    @Test
    void write_whenTheLastRunFailedButTheImportIsNotBehind_thenItSaysOnlyThat() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(new DocumentationFacts.EnvironmentFacts("prod", "Production", true, false, true,
                        GENERATED_AT.minus(Duration.ofMinutes(20)), ImportOutcome.FAILED, Duration.ofHours(2))),
                new DocumentationFacts.Schedules(null, null, null, null));

        String written = write(facts, 1L);

        assertThat(written).contains("; the last run did not read it").doesNotContain("not read since");
    }

    @Test
    void write_thenTheSchedulesSayWhenTheDocumentationChangesNext() throws IOException {
        String written = write(facts(), 1L);

        assertThat(written)
                .contains("`0 5 6-20 * * *`")
                .contains("in 35 minutes")
                .contains("`0 45 5-19 * * *`");
    }

    /** A site published only on upload has no schedule, and the page says that rather than nothing. */
    @Test
    void write_whenTheSiteHasNoPublicationSchedule_thenItSaysSoRatherThanLeavingTheCellEmpty()
            throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT), site(),
                List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null, null, null));

        String written = write(facts, 1L);

        assertThat(written).contains("*only when something is uploaded to it*");
    }

    @Test
    void write_whenTheVersionCannotBeRead_thenThePageSaysNothingAboutIt() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service(null, GENERATED_AT), site(), List.of(environmentFacts()),
                new DocumentationFacts.Schedules(null, null, null, null));

        String written = write(facts, 1L);

        assertThat(written).contains("generated by the jEAP Doc Service.").doesNotContain("null");
    }

    @Test
    void spellOut_thenADurationAsAReaderSaysIt() {
        assertThat(AboutThisDocumentation.spellOut(Duration.ofSeconds(20))).isEqualTo("in a moment");
        assertThat(AboutThisDocumentation.spellOut(Duration.ofMinutes(1))).isEqualTo("in 1 minute");
        assertThat(AboutThisDocumentation.spellOut(Duration.ofMinutes(35))).isEqualTo("in 35 minutes");
        assertThat(AboutThisDocumentation.spellOut(Duration.ofMinutes(60))).isEqualTo("in 1 hour");
        assertThat(AboutThisDocumentation.spellOut(Duration.ofMinutes(125))).isEqualTo("in 2 hours 5 minutes");
        assertThat(AboutThisDocumentation.spellOut(Duration.ofMinutes(-5))).isEqualTo("in a moment");
    }

    private String write(DocumentationFacts facts, long buildId) throws IOException {
        page.write(facts, new SiteEnvironment("prod", "PROD", "Production", 1, true, false),
                Map.of("prod", new EnvironmentModel(2, 5, 9, IMPORTED_AT)), buildId, STATUS_URL, directory);
        return Files.readString(directory.resolve(AboutThisDocumentation.FILE_NAME), StandardCharsets.UTF_8);
    }

    private static DocumentationFacts facts() {
        return new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT),
                site(),
                List.of(environmentFacts(),
                        new DocumentationFacts.EnvironmentFacts("dev", "Development", false, true, false,
                                null, null, Duration.ofHours(2))),
                new DocumentationFacts.Schedules("0 5 6-20 * * *", GENERATED_AT.plus(Duration.ofMinutes(35)),
                        "0 45 5-19 * * *", GENERATED_AT.plus(Duration.ofMinutes(15))));
    }

    /**
     * <b>A page that contradicts itself is a support call.</b> Every test above builds the same site - with a
     * structure template, and publishing on upload - so neither of the two branches the page carries for the
     * other configuration was written by any of them. These three are that configuration.
     */
    @Test
    void write_whenAnUploadDoesNotPublishTheSite_thenThePageSaysSoOnlyOnce() throws IOException {
        DocumentationFacts all = facts();
        DocumentationFacts facts = new DocumentationFacts(all.service(),
                new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                        List.of("System Architecture"), true, false, 3),
                all.environments(),
                new DocumentationFacts.Schedules(null, null, "0 45 5-19 * * *",
                        GENERATED_AT.plus(Duration.ofMinutes(15))));

        String written = write(facts, 4711L);

        assertThat(written)
                .contains("| An upload publishes the site | no |")
                .contains("*only when an operator asks for it*")
                .describedAs("the paragraph that says the opposite belongs to the other configuration")
                .doesNotContain("as soon as it arrives");
    }

    @Test
    void write_whenThereIsNoStructureTemplate_thenWhatIsStillGeneratedIsNamed() throws IOException {
        String written = write(factsOf(new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                List.of(), true, true, 3)), 4711L);

        assertThat(written)
                .describedAs("an environment of this site does read a model, so those pages exist")
                .contains("*none - only the system index and the landing pages are generated*");
    }

    /**
     * With no architecture repository for any environment, {@code SystemPages.write} returns before it creates
     * a directory - so neither a system index nor a landing page exists, and naming them would be the same
     * untruth the other way round.
     */
    @Test
    void write_whenNoEnvironmentReadsAModel_thenNoGeneratedPagesAreClaimed() throws IOException {
        DocumentationFacts facts = new DocumentationFacts(
                new DocumentationFacts.Service("1.2.3", GENERATED_AT),
                new DocumentationFacts.SiteFacts("default", "Platform Documentation", List.of(), false, true, 3),
                List.of(new DocumentationFacts.EnvironmentFacts("prod", "Production", true, true, false,
                        null, null, Duration.ofHours(2))),
                new DocumentationFacts.Schedules("0 5 6-20 * * *", GENERATED_AT.plus(Duration.ofMinutes(35)),
                        null, null));

        String written = write(facts, 4711L);

        assertThat(written).contains("| Documentation structures | *none* |")
                .doesNotContain("the system index and the landing pages");
    }

    private static DocumentationFacts factsOf(DocumentationFacts.SiteFacts site) {
        DocumentationFacts all = facts();
        return new DocumentationFacts(all.service(), site, all.environments(), all.schedules());
    }

    private static DocumentationFacts.SiteFacts site() {
        return new DocumentationFacts.SiteFacts("default", "Platform Documentation",
                List.of("System Architecture"), true, true, 3);
    }

    private static DocumentationFacts.EnvironmentFacts environmentFacts() {
        return new DocumentationFacts.EnvironmentFacts("prod", "Production", true, false, true,
                Instant.parse("2026-09-03T07:15:00Z"), ImportOutcome.UNCHANGED, Duration.ofHours(2));
    }
}
