package ch.admin.bit.jeap.doc.template.arc42;

import ch.admin.bit.jeap.doc.domain.template.GenerationContext;
import ch.admin.bit.jeap.doc.domain.template.StructureChapter;
import ch.admin.bit.jeap.doc.domain.template.StructureTemplate;
import ch.admin.bit.jeap.doc.markdown.CategoryFile;
import ch.admin.bit.jeap.doc.markdown.FrontMatter;
import ch.admin.bit.jeap.doc.markdown.MarkdownWriter;
import ch.admin.bit.jeap.doc.markdown.Md;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static ch.admin.bit.jeap.doc.markdown.FrontMatter.frontMatter;

/** What every generated arc42 page has in common: its front matter, its provenance, and how it is written. */
final class Arc42Pages {

    /** The file a folder's landing page is written to, which Docusaurus fixes. */
    static final String INDEX = "index.md";

    private Arc42Pages() {
    }

    /**
     * The front matter of a generated page.
     * <p>
     * {@code doc_status} is what makes <i>generated or custom, never both</i> checkable. Uploaded pages will
     * carry {@code custom}, so nothing has to guess which of the two a page is.
     */
    static FrontMatter generated(String title, int position, GenerationContext context) {
        return frontMatter()
                .put("title", title)
                .put("sidebar_label", title)
                .put("sidebar_position", position)
                .put("doc_status", "generated")
                .put("doc_source", "archrepo")
                .put("doc_source_url", context.archRepoUrl())
                .put("doc_environment", context.environment())
                .put("doc_model_imported_at", context.hasModelImportedAt()
                        ? context.modelImportedAt().toString() : null)
                .put("doc_generated_at", context.generatedAt().toString());
    }

    /**
     * The sentence at the foot of a generated page: <i>the source is recognizable on every page</i>, written
     * for a reader rather than for a machine.
     */
    static MarkdownWriter provenance(MarkdownWriter page, GenerationContext context) {
        // Two timestamps, because they answer two different questions now that the model is imported on a
        // schedule of its own: how current the content is, and when the page was last written.
        return page.admonition("info", "Generated page", context.hasModelImportedAt()
                ? Md.sentence("Generated by the jEAP Doc Service from the architecture model of the {} "
                              + "environment, imported {}, page built {}.",
                Md.bold(context.environment()), Md.text(context.modelImportedAtDisplay()),
                Md.text(context.generatedAtDisplay()))
                : Md.sentence("Generated by the jEAP Doc Service from the architecture model of the {} "
                              + "environment on {}.",
                Md.bold(context.environment()), Md.text(context.generatedAtDisplay())));
    }

    /** Writes a page, creating the folders it needs. */
    static void write(Path directory, String fileName, MarkdownWriter page) throws IOException {
        Files.createDirectories(directory);
        Files.writeString(directory.resolve(fileName), page.text(), StandardCharsets.UTF_8);
    }

    /** Writes the {@code _category_.json} that names a folder and places it in the navigation. */
    static void writeCategory(Path directory, String label, int position) throws IOException {
        Files.createDirectories(directory);
        Files.writeString(directory.resolve(CategoryFile.NAME), CategoryFile.of(label, position),
                StandardCharsets.UTF_8);
    }

    /**
     * The folder of a chapter, with the {@code _category_.json} that gives it its label and its place in the
     * sidebar.
     * <p>
     * The place comes from the template rather than from the chapter, because it is the template that knows how
     * its chapters are ordered - by their numbers here, by their titles in a methodology that does not number
     * them. See {@link StructureTemplate#positionOf}.
     */
    static Path chapterDirectory(StructureTemplate template, Path structureDirectory, StructureChapter chapter)
            throws IOException {
        Path directory = structureDirectory.resolve(chapter.folder());
        writeCategory(directory, chapter.label(), template.positionOf(chapter));
        return directory;
    }
}
