package ch.admin.bit.jeap.doc.markdown;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.util.List;

import static ch.admin.bit.jeap.doc.markdown.FrontMatter.frontMatter;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class MarkdownWriterTest {

    @Test
    void frontMatter_isTheFirstThingOnThePage_andEveryValueIsQuoted() {
        String page = new MarkdownWriter()
                .frontMatter(frontMatter()
                        .put("title", "jEAP: Documentation")
                        .put("sidebar_position", 5)
                        .put("doc_status", "generated"))
                .heading(1, "jEAP: Documentation")
                .text();

        assertThat(page).isEqualTo("""
                ---
                title: "jEAP: Documentation"
                sidebar_position: 5
                doc_status: "generated"
                ---

                # jEAP: Documentation
                """);
    }

    @Test
    void frontMatter_whenSomethingIsAlreadyWritten_thenItIsRefused() {
        MarkdownWriter writer = new MarkdownWriter().heading(1, "Too late");
        assertThatThrownBy(() -> writer.frontMatter(frontMatter().put("title", "x")))
                .isInstanceOf(IllegalStateException.class);
    }

    @Test
    void blocks_areSeparatedByExactlyOneBlankLine() {
        String page = new MarkdownWriter()
                .heading(1, "Title")
                .paragraph("First.")
                .heading(2, "Section")
                .paragraph("Second.")
                .text();

        assertThat(page).isEqualTo("""
                # Title

                First.

                ## Section

                Second.
                """);
    }

    @Test
    void table_writesTheAlignmentRowAndEscapesThePipeInACell() {
        String page = new MarkdownWriter()
                .table(List.of("Component", "Description"),
                        List.of(List.of(Md.code("orders-foo"), Md.text("does a | b")),
                                List.of(Md.code("orders-bar"), Markdown.EMPTY)))
                .text();

        assertThat(page).isEqualTo("""
                | Component | Description |
                | --- | --- |
                | `orders-foo` | does a \\| b |
                | `orders-bar` | - |
                """);
    }

    @Test
    void table_flattensALineBreakInACell() {
        String page = new MarkdownWriter()
                .table(List.of("A"), List.of(List.of(Md.text("first\nsecond"))))
                .text();
        assertThat(page).contains("| first second |");
    }

    /**
     * A row of the wrong width renders as a table with a missing cell rather than as an error, which is exactly
     * the kind of defect nobody reports.
     */
    @Test
    void table_whenARowDoesNotMatchTheHeader_thenItFails() {
        MarkdownWriter writer = new MarkdownWriter();
        assertThatThrownBy(() -> writer.table(List.of("A", "B"), List.of(List.of(Md.text("only one")))))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("2 columns");
    }

    @Test
    void bulletList_writesNothingWhenThereIsNothing() {
        assertThat(new MarkdownWriter().bulletList(List.of()).text()).isEmpty();
    }

    @Test
    void fence_passesTheBodyThroughUntouched() {
        String page = new MarkdownWriter().fence("plantuml", "@startuml\ncomponent \"a|b\"\n@enduml").text();
        assertThat(page).isEqualTo("""
                ```plantuml
                @startuml
                component "a|b"
                @enduml
                ```
                """);
    }

    @Test
    void fence_whenTheBodyCarriesAFence_thenTheOuterOneIsLonger() {
        String page = new MarkdownWriter().fence("dot", "a\n```\nb").text();
        assertThat(page).startsWith("````dot\n").endsWith("````\n");
    }

    @Test
    void fence_whenTheLanguageIsNotAWord_thenItIsRefused() {
        MarkdownWriter writer = new MarkdownWriter();
        assertThatThrownBy(() -> writer.fence("Plant UML", "x")).isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void admonition_isWrittenAsDocusaurusReadsIt() {
        String page = new MarkdownWriter()
                .admonition("info", "Generated page", Md.text("Generated by the jEAP Doc Service."))
                .text();

        assertThat(page).isEqualTo("""
                :::info[Generated page]

                Generated by the jEAP Doc Service.

                :::
                """);
    }

    @Test
    void admonition_whenThereIsNothingToSay_thenItIsRefused() {
        MarkdownWriter writer = new MarkdownWriter();
        assertThatThrownBy(() -> writer.admonition("info", "Title", Markdown.EMPTY))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void hasContent_ignoresTheFrontMatter() {
        MarkdownWriter writer = new MarkdownWriter().frontMatter(frontMatter().put("title", "x"));
        assertThat(writer.hasContent()).isFalse();
        writer.paragraph("Something.");
        assertThat(writer.hasContent()).isTrue();
    }

    @Test
    void paragraph_whenThereIsNothing_thenNothingIsWritten() {
        assertThat(new MarkdownWriter().paragraph(Markdown.EMPTY).text()).isEmpty();
    }

    @Test
    void paragraphOrNothing_saysSoRatherThanLeavingTheSectionEmpty() {
        assertThat(new MarkdownWriter().paragraphOrNothing(Markdown.EMPTY, "None.").text()).isEqualTo("None.\n");
    }

    @Test
    void heading_isBetweenOneAndFour() {
        MarkdownWriter writer = new MarkdownWriter();
        assertThatThrownBy(() -> writer.heading(0, "x")).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> writer.heading(5, "x")).isInstanceOf(IllegalArgumentException.class);
    }

    /**
     * An imported description is free text, and a description that happens to begin with a bullet, a number or
     * three dashes must read as what it says rather than turn the page into a list, an ordered list or a
     * thematic break. The escaped character renders as itself, so nothing about the page reads differently.
     */
    @ParameterizedTest
    @CsvSource(delimiter = '|', quoteCharacter = '\'', textBlock = """
            '- an item'      | '\\- an item'
            '+ an item'      | '\\+ an item'
            '--- a break'    | '\\--- a break'
            '1. the first'   | '1\\. the first'
            '2) the second'  | '2\\) the second'
            'a - b'          | 'a - b'
            'version 1.0.0'  | 'version 1.0.0'
            """)
    void paragraph_whenItWouldOpenABlock_thenTheOpenerIsEscaped(String value, String expected) {
        assertThat(new MarkdownWriter().paragraph(value).text()).isEqualTo(expected + "\n");
    }

    /**
     * A heading is not a paragraph: after {@code ## } an ordered-list marker means nothing, and every arc42
     * chapter title begins with one. Escaping there would put a backslash in front of every chapter.
     */
    @Test
    void heading_whenItBeginsWithANumber_thenNothingIsEscaped() {
        assertThat(new MarkdownWriter().heading(1, "1. Introduction and Goals").text())
                .isEqualTo("# 1. Introduction and Goals\n");
    }
}
