package ch.admin.bit.jeap.doc.web.site.browser;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Response;
import com.microsoft.playwright.assertions.PlaywrightAssertions;
import com.microsoft.playwright.options.AriaRole;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * What a reader gets from documentation a team wrote: the page, its place in the navigation, and where it
 * says it came from.
 * <p>
 * The site this drives has a system no architecture model holds, documented entirely by uploads - so nothing
 * that passes here can be coming from the generated half.
 */
class CustomDocsBrowserIT extends SiteBrowserTestBase {

    @Test
    void anUploadedPage_isServedInItsChapter() {
        Response response = open("/" + DOCUMENTED_CHAPTER_ROUTE + "/zzz-first/");

        assertThat(response.status()).isEqualTo(200);
        PlaywrightAssertions.assertThat(page.getByRole(AriaRole.HEADING,
                        new Page.GetByRoleOptions()
                                .setName("A " + UploadedDocumentation.GLOSSARY_WORD + " and what it is")
                                .setLevel(1)))
                .isVisible();
        PlaywrightAssertions.assertThat(
                page.getByText("Written by the team that owns this documentation.")).isVisible();
    }

    /**
     * <b>The order of a chapter is the service's answer, not Docusaurus'.</b> An autogenerated sidebar is
     * sorted by position and then by file name, and these two pages are named the other way round on
     * purpose: file names alone would put {@code aaa-second} first.
     */
    @Test
    void thePagesOfAChapter_areInTheOrderOfTheirTitles() {
        open("/" + DOCUMENTED_CHAPTER_ROUTE + "/zzz-first/");

        Locator links = page.locator("nav.menu a.menu__link");
        List<String> titles = links.allInnerTexts().stream()
                .filter(text -> text.startsWith("A " + UploadedDocumentation.GLOSSARY_WORD)
                                || text.startsWith("Z is for"))
                .toList();

        assertThat(titles).describedAs("by title, though the file names would give the opposite")
                .containsExactly("A " + UploadedDocumentation.GLOSSARY_WORD + " and what it is",
                        "Z is for the last word");
    }

    /**
     * The chapter exists only because a page was uploaded into it - chapter 12 is one of the eight the
     * generator never writes - and a reader who opens it has to land on something.
     */
    @Test
    void aChapterNothingGenerates_hasALandingPageOfItsOwn() {
        Response response = open("/" + DOCUMENTED_CHAPTER_ROUTE + "/");

        assertThat(response.status()).isEqualTo(200);
        PlaywrightAssertions.assertThat(page.getByRole(AriaRole.HEADING,
                new Page.GetByRoleOptions().setName("Glossary").setLevel(1))).isVisible();
    }

    @Test
    void anUploadedPage_saysWhichRepositoryItCameFrom() {
        open("/" + DOCUMENTED_CHAPTER_ROUTE + "/zzz-first/");

        Locator provenance = page.getByLabel("Where this page came from");
        PlaywrightAssertions.assertThat(provenance).isVisible();
        PlaywrightAssertions.assertThat(provenance).containsText("Written by the team");
        PlaywrightAssertions.assertThat(provenance).containsText(UploadedDocumentation.REPOSITORY);
        PlaywrightAssertions.assertThat(provenance).containsText(UploadedDocumentation.REVISION);
    }

    /**
     * The same block, in the same place, on a page the service wrote itself - which is what makes
     * <i>generated or custom</i> something a reader sees rather than something the front matter records.
     * <p>
     * The page it uses is one the template really generated. Most pages of this suite's site are written by
     * hand to suit a test and carry no {@code doc_status}, and a page with none renders no block at all.
     */
    @Test
    void aGeneratedPage_saysSoInTheSamePlace() {
        open("/systems/" + DOCUMENTED_SYSTEM
             + "/system-architecture/intro/not-in-the-architecture-model/");

        Locator provenance = page.getByLabel("Where this page came from");
        PlaywrightAssertions.assertThat(provenance).isVisible();
        PlaywrightAssertions.assertThat(provenance).containsText("Generated page");
        PlaywrightAssertions.assertThat(provenance).containsText("architecture model");
    }

    /**
     * <b>And a generated page the architecture model had no part in must not claim it did.</b> The page
     * describing the documentation is written from the doc service's own configuration and records - it says
     * so in its {@code doc_source} - and the block used to read the status alone and tell every reader it came
     * from the architecture model.
     */
    @Test
    void thePageDescribingTheDocumentation_saysItComesFromTheServiceAndNotFromTheModel() {
        assertThat(open("/about-this-documentation/").status()).isEqualTo(200);

        Locator provenance = page.getByLabel("Where this page came from");
        PlaywrightAssertions.assertThat(provenance).isVisible();
        PlaywrightAssertions.assertThat(provenance).containsText("Generated page");
        PlaywrightAssertions.assertThat(provenance)
                .containsText("its own configuration and records");
        // A page with a generation date and no import names that date instead.
        PlaywrightAssertions.assertThat(provenance).containsText("generated");
    }

    /**
     * A system nothing has deployed: one generated page says what is missing, and the chapters the team
     * wrote are there as they would be for any other system.
     */
    @Test
    void aSystemNoArchitectureModelHolds_saysSoAndShowsWhatWasWritten() {
        Response response = open("/systems/" + DOCUMENTED_SYSTEM
                                 + "/system-architecture/intro/not-in-the-architecture-model/");

        assertThat(response.status()).isEqualTo(200);
        PlaywrightAssertions.assertThat(page.getByText("does not hold the system")).isVisible();
        assertThat(open("/" + DOCUMENTED_CHAPTER_ROUTE + "/zzz-first/").status()).isEqualTo(200);
        assertThat(open("/systems/" + DOCUMENTED_SYSTEM
                        + "/system-architecture/context-and-scope/system-context-view/").status())
                .describedAs("and nothing is generated from a model that does not hold it")
                .isEqualTo(404);
    }
}
