package ch.admin.bit.jeap.doc.domain.custom;

import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/** What survives of a page's front matter, and what is added to it. */
class UploadedFrontMatterTest {

    private static Map<String, Object> generated() {
        Map<String, Object> keys = UploadedFrontMatter.keys();
        keys.put("sidebar_position", 3);
        keys.put("doc_status", "custom");
        return keys;
    }

    @Test
    void anAllowlistedKey_keepsItsValue() {
        String rewritten = UploadedFrontMatter.rewritten("""
                ---
                title: "Quality: what we measure"
                description: the scenarios
                ---

                # Quality
                """, generated());

        assertThat(rewritten)
                .describedAs("the value, with the quoting the published block needs rather than the one the "
                             + "page happened to use")
                .contains("title: 'Quality: what we measure'");
        assertThat(rewritten).contains("description: the scenarios");
        assertThat(rewritten).contains("sidebar_position: 3").contains("doc_status: custom");
    }

    @Test
    void theBody_isLeftAloneEntirely() {
        String body = """
                # Constraints

                A fenced block that is never closed:

                ```java
                var x = 1;
                """;

        String rewritten = UploadedFrontMatter.rewritten("---\ntitle: C\n---\n\n" + body, generated());

        assertThat(rewritten).endsWith(body);
    }

    @Test
    void aKeyThatIsNotAllowed_isDropped() {
        String rewritten = UploadedFrontMatter.rewritten("""
                ---
                title: Goals
                slug: /somewhere-else
                doc_status: generated
                id: something
                ---

                # Goals
                """, generated());

        assertThat(rewritten).doesNotContain("slug:").doesNotContain("id: something");
        assertThat(rewritten).describedAs("a page cannot claim to be generated by saying so")
                .containsOnlyOnce("doc_status:").contains("doc_status: custom");
    }

    @Test
    void aBlockList_keepsItsItems() {
        String rewritten = UploadedFrontMatter.rewritten("""
                ---
                title: Glossary
                tags:
                  - terms
                  - abbreviations
                description: what the words mean
                ---

                # Glossary
                """, generated());

        assertThat(rewritten).contains("tags:").contains("  - terms").contains("  - abbreviations");
        assertThat(rewritten).contains("description: what the words mean");
    }

    @Test
    void theItemsOfAKeyThatIsNotAllowed_areDroppedWithIt() {
        String rewritten = UploadedFrontMatter.rewritten("""
                ---
                sidebar_custom_props:
                  featured: true
                title: Goals
                ---

                # Goals
                """, generated());

        assertThat(rewritten).doesNotContain("sidebar_custom_props").doesNotContain("featured");
        assertThat(rewritten).contains("title: Goals");
    }

    @Test
    void aPageWithNoFrontMatter_getsOneAndKeepsItsBody() {
        String rewritten = UploadedFrontMatter.rewritten("# Just a heading\n\nAnd text.\n", generated());

        assertThat(rewritten).startsWith("---\n").contains("doc_status: custom")
                .endsWith("# Just a heading\n\nAnd text.\n");
    }

    /**
     * A block that is never closed cannot be told from the body, so the page keeps none of it as front
     * matter: what was inside the block becomes text, and the page gets the generated keys and nothing else.
     */
    @Test
    void aFrontMatterThatIsNeverClosed_leavesThePageWithoutOne() {
        String rewritten = UploadedFrontMatter.rewritten("---\ntitle: Goals\n\n# Goals\n", generated());

        assertThat(rewritten).isEqualTo("""
                ---
                sidebar_position: 3
                doc_status: custom
                ---

                title: Goals

                # Goals
                """);
    }

    @Test
    void aByteOrderMark_doesNotHideTheBlock() {
        String rewritten = UploadedFrontMatter.rewritten("﻿---\ntitle: Goals\n---\n\n# Goals\n",
                generated());

        assertThat(rewritten).contains("title: Goals");
    }

    @Test
    void aPageOfNothingButFrontMatter_isStillAPage() {
        String rewritten = UploadedFrontMatter.rewritten("---\ntitle: Goals\n---\n", generated());

        assertThat(rewritten).isEqualTo("---\ntitle: Goals\nsidebar_position: 3\ndoc_status: custom\n---\n");
    }

    @Test
    void theGeneratedKeys_areWrittenInTheOrderTheyWerePutIn() {
        Map<String, Object> keys = new LinkedHashMap<>();
        keys.put("first", "1");
        keys.put("second", "2");

        assertThat(UploadedFrontMatter.rewritten("# a page\n", keys))
                .contains("first: '1'\nsecond: '2'");
    }

    /**
     * A quoted scalar may legally run over several lines, and YAML does not require the continuation to be
     * indented. It is the shape a line-based reading cannot follow at all - it used to drop the key, and
     * before that it kept an opening quote that swallowed every key the service adds after it and failed the
     * build of the whole part on YAML, minutes later. Parsed, it is simply the value it says it is.
     */
    @Test
    void rewritten_whenAQuotedValueRunsOverSeveralLines_thenItIsTheValueItSays() {
        String page = """
                ---
                title: "a title that runs
                over two lines"
                description: The short one
                ---

                Text.
                """;

        String rewritten = UploadedFrontMatter.rewritten(page, generated());

        assertThat(rewritten)
                .describedAs("YAML folds the line break of a quoted scalar into a space")
                .contains("title: a title that runs over two lines");
        assertThat(rewritten)
                .contains("description: The short one")
                .contains("doc_status: custom");
    }

    /** Whatever quoting a page used, what is published is quoting the reader of it will agree with. */
    @Test
    void rewritten_thenTheQuotingIsTheOneThePublishedValueNeeds() {
        String page = """
                ---
                title: "Why: the short version"
                description: 'it is quoted too'
                sidebar_label: "an \\"escaped\\" label"
                ---

                Text.
                """;

        String rewritten = UploadedFrontMatter.rewritten(page, generated());

        assertThat(rewritten)
                .describedAs("a colon needs quotes, and one pair of them is enough")
                .contains("title: 'Why: the short version'");
        assertThat(rewritten)
                .describedAs("and a value that needs none is left plain")
                .contains("description: it is quoted too");
        assertThat(rewritten).contains("sidebar_label: an \"escaped\" label");
    }

    /**
     * <b>A value that would be read back as something else is quoted.</b> An instant written plainly is a
     * YAML timestamp, and the site template would render a date object where the page means to name the
     * moment it was uploaded.
     */
    @Test
    void rewritten_whenAGeneratedValueLooksLikeADate_thenItIsPublishedAsText() {
        Map<String, Object> keys = UploadedFrontMatter.keys();
        keys.put("doc_uploaded_at", "2026-09-01T10:05:00Z");
        keys.put("doc_version", "1.4.0");

        assertThat(UploadedFrontMatter.rewritten("# a page\n", keys))
                .contains("doc_uploaded_at: '2026-09-01T10:05:00Z'")
                .describedAs("and so is a version, which would otherwise read as a number")
                .contains("doc_version: 1.4.0");
    }

    /** A number is a number: Docusaurus orders a sidebar by it, and a quoted one is a string. */
    @Test
    void rewritten_whenAGeneratedValueIsANumber_thenItIsPublishedAsOne() {
        Map<String, Object> keys = UploadedFrontMatter.keys();
        keys.put("sidebar_position", 101);

        assertThat(UploadedFrontMatter.rewritten("# a page\n", keys))
                .contains("sidebar_position: 101");
    }

    /**
     * <b>Front matter is read with a constructor that builds nothing but collections and scalars.</b> The
     * content is a team's upload: a reader that instantiated the types a document names would be a
     * deserialization sink, and a page naming one is a page with no front matter.
     */
    @Test
    void rewritten_whenTheBlockNamesAJavaType_thenItIsNotConstructed() {
        String page = """
                ---
                title: !!javax.script.ScriptEngineManager [!!java.net.URLClassLoader [[!!java.net.URL ["http://x"]]]]
                description: The short one
                ---

                Text.
                """;

        String rewritten = UploadedFrontMatter.rewritten(page, generated());

        assertThat(rewritten)
                .describedAs("the block does not parse, so the page carries none of it")
                .doesNotContain("ScriptEngineManager")
                .doesNotContain("description: The short one");
        assertThat(rewritten).contains("doc_status: custom");
    }

    /**
     * <b>A value of the wrong kind fails the build of a whole part.</b> Docusaurus validates a document's
     * front matter and throws on a title that is a list or keywords that are a scalar - so a page carrying
     * one is published without that key rather than with it.
     */
    @Test
    void rewritten_whenAnAllowedKeyHasAValueTheSiteCannotTake_thenThatKeyIsDropped() {
        String page = """
                ---
                title:
                  - one
                  - two
                description:
                  nested: mapping
                keywords: not-a-list
                sidebar_label: The label
                ---

                Text.
                """;

        String rewritten = UploadedFrontMatter.rewritten(page, generated());

        assertThat(rewritten)
                .doesNotContain("- one")
                .doesNotContain("nested")
                .doesNotContain("keywords:");
        assertThat(rewritten)
                .describedAs("and everything else the page said about itself survives")
                .contains("sidebar_label: The label")
                .contains("doc_status: custom");
    }

    /**
     * <b>A blank title is no title, in both readers.</b> {@code UploadedTitles} sorts such a page by its file
     * name; keeping the key here would publish an empty title in the sidebar and in the heading of a page the
     * navigation says has none.
     */
    @Test
    void rewritten_whenAnAllowedKeyIsBlank_thenItIsNotPublished() {
        String page = """
                ---
                title: ""
                description: "   "
                sidebar_label: The label
                ---

                Text.
                """;

        String rewritten = UploadedFrontMatter.rewritten(page, generated());

        assertThat(rewritten).doesNotContain("title:").doesNotContain("description:");
        assertThat(rewritten).contains("sidebar_label: The label");
    }

    /** And a list of nothing but blanks is a list the page did not really carry. */
    @Test
    void rewritten_whenAListKeyHoldsOnlyBlanks_thenItIsNotPublished() {
        assertThat(UploadedFrontMatter.rewritten("---\ntags:\n  - \"\"\n  - \"  \"\n---\n\nText.\n", generated()))
                .doesNotContain("tags:");
    }

    /** A list of scalars is what the two list keys are for, and it is kept. */
    @Test
    void rewritten_whenAListKeyHoldsScalars_thenItIsKept() {
        String page = """
                ---
                tags:
                  - glossary
                  - terms
                ---

                Text.
                """;

        assertThat(UploadedFrontMatter.rewritten(page, generated()))
                .contains("tags:")
                .contains("- glossary")
                .contains("- terms");
    }

    /**
     * A plain {@code 2024-01-01} is a YAML timestamp, so a title written that way parses as a date. It is
     * published as the text the page meant rather than as a date object the site template cannot render.
     */
    @Test
    void rewritten_whenATitleLooksLikeADate_thenItIsPublishedAsText() {
        assertThat(UploadedFrontMatter.rewritten("---\ntitle: 2024-01-01\n---\n\nText.\n", generated()))
                .contains("title: '2024-01-01'");
    }

    /** An expansion bomb is a handful of bytes, and no page needs an alias. */
    @Test
    void rewritten_whenTheBlockIsAnExpansionBomb_thenItIsRefusedRatherThanExpanded() {
        String page = """
                ---
                a: &a ["x","x","x","x","x","x","x","x","x"]
                b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]
                title: *b
                ---

                Text.
                """;

        assertThat(UploadedFrontMatter.rewritten(page, generated()))
                .doesNotContain("title:")
                .contains("doc_status: custom");
    }
}
