package ch.admin.bit.jeap.doc.domain.upload;

/**
 * The format uploaded documents are written in. Markdown documents are rendered by the doc service, HTML
 * documents are generated by the uploading build and embedded into a section of the documentation.
 */
public enum SourceFormat {

    MARKDOWN,
    HTML
}
