package ch.admin.bit.jeap.doc.web.api;

import java.util.Arrays;
import java.util.stream.Collectors;

/**
 * The format the uploaded documents are written in. Markdown documents are rendered by the doc service, HTML
 * documents are generated by the uploading build and embedded into a section of the documentation.
 */
public enum SourceFormat {

    MARKDOWN("markdown"),
    HTML("html");

    private final String parameterValue;

    SourceFormat(String parameterValue) {
        this.parameterValue = parameterValue;
    }

    public String parameterValue() {
        return parameterValue;
    }

    public static SourceFormat fromParameterValue(String value) {
        return Arrays.stream(values())
                .filter(format -> format.parameterValue.equals(value))
                .findFirst()
                .orElseThrow(() -> InvalidUploadException.invalidValue("source-format", value, acceptedValues()));
    }

    public static String acceptedValues() {
        return Arrays.stream(values()).map(SourceFormat::parameterValue).collect(Collectors.joining(", "));
    }
}
